"""init migration

Revision ID: 108a8ff0a18d
Revises:
Create Date: 2024-10-05 10:36:58.183414

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "108a8ff0a18d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
